apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: mywebapp

configMapGenerator:
- name: mykustom-map
  envs:
  - config.properties
