# Correct patches format
patches:
  - path: patch1.yaml
    target:
      kind: Deployment
  - path: patch2.yaml

# OR correct patchesStrategicMerge format
patchesStrategicMerge:
  - patch1.yaml
  - patch2.yaml
